/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ModuleModelService } from "../moduleModel.service";
import { ModuleModelCreateInput } from "./ModuleModelCreateInput";
import { ModuleModel } from "./ModuleModel";
import { Post } from "../../post/base/Post";
import { ModuleModelFindManyArgs } from "./ModuleModelFindManyArgs";
import { ModuleModelWhereUniqueInput } from "./ModuleModelWhereUniqueInput";
import { ModuleModelUpdateInput } from "./ModuleModelUpdateInput";
import { LessonFindManyArgs } from "../../lesson/base/LessonFindManyArgs";
import { Lesson } from "../../lesson/base/Lesson";
import { LessonWhereUniqueInput } from "../../lesson/base/LessonWhereUniqueInput";

export class ModuleModelControllerBase {
  constructor(protected readonly service: ModuleModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ModuleModel })
  async createModuleModel(
    @common.Body() data: ModuleModelCreateInput
  ): Promise<ModuleModel> {
    return await this.service.createModuleModel({
      data: {
        ...data,

        course: data.course
          ? {
              connect: data.course,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,

        course: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ModuleModel] })
  @ApiNestedQuery(ModuleModelFindManyArgs)
  async moduleModels(@common.Req() request: Request): Promise<ModuleModel[]> {
    const args = plainToClass(ModuleModelFindManyArgs, request.query);
    return this.service.moduleModels({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,

        course: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async moduleModel(
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<ModuleModel | null> {
    const result = await this.service.moduleModel({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,

        course: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateModuleModel(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() data: ModuleModelUpdateInput
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.updateModuleModel({
        where: params,
        data: {
          ...data,

          course: data.course
            ? {
                connect: data.course,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          title: true,

          course: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteModuleModel(
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.deleteModuleModel({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          title: true,

          course: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/lessons")
  @ApiNestedQuery(LessonFindManyArgs)
  async findLessons(
    @common.Req() request: Request,
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<Lesson[]> {
    const query = plainToClass(LessonFindManyArgs, request.query);
    const results = await this.service.findLessons(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        content: true,

        moduleModel: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/lessons")
  async connectLessons(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() body: LessonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessons: {
        connect: body,
      },
    };
    await this.service.updateModuleModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/lessons")
  async updateLessons(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() body: LessonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessons: {
        set: body,
      },
    };
    await this.service.updateModuleModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/lessons")
  async disconnectLessons(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() body: LessonWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      lessons: {
        disconnect: body,
      },
    };
    await this.service.updateModuleModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
